modLoader = "javafml"
loaderVersion = "[%FORGE_LOADER_MAJOR%,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "%MOD_ID%"
version = "${version}"
displayName = "%MOD_NAME_TOML%"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.%MOD_ID%]]
modId = "forge"
mandatory = true
versionRange = "[%FORGE_LOADER_MAJOR%,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.%MOD_ID%]]
modId = "minecraft"
mandatory = true
versionRange = "[%MINECRAFT_VERSION%,)"
ordering = "NONE"
side = "BOTH"
#% if architectury_api

[[dependencies.%MOD_ID%]]
modId = "architectury"
mandatory = true
versionRange = "[%ARCHITECTURY_API_VERSION%,)"
ordering = "AFTER"
side = "BOTH"
#% end
